# Generated by Django 5.0.2 on 2024-03-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentstatus',
            options={'verbose_name_plural': 'Employment Status'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
