# Generated by Django 5.0.2 on 2024-03-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_employmentstatus_options_alter_faqs_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
