# Generated by Django 5.0.2 on 2024-03-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password2',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
