# Generated by Django 5.0.2 on 2024-03-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_remove_student_password1_remove_student_password2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Name', max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=100)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gender')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('guardian_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.guardianrelation')),
            ],
        ),
    ]
