# Generated by Django 5.0.2 on 2024-03-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='StudentApplication',
        ),
    ]
