# Generated by Django 5.0.2 on 2024-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_rename_application_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
