# Generated by Django 5.0.2 on 2024-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_remove_staff_name_staff_first_name_staff_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
