# Generated by Django 5.0.2 on 2024-03-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_staff_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='role',
            new_name='designation',
        ),
    ]
