# Generated by Django 5.0.2 on 2024-03-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_rename_role_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_one_from', models.TimeField()),
                ('period_one_to', models.TimeField()),
                ('period_two_from', models.TimeField()),
                ('period_two_to', models.TimeField()),
                ('period_three_from', models.TimeField()),
                ('period_three_to', models.TimeField()),
                ('period_four_from', models.TimeField()),
                ('period_four_to', models.TimeField()),
                ('period_five_from', models.TimeField()),
                ('period_five_to', models.TimeField()),
                ('period_six_from', models.TimeField()),
                ('period_six_to', models.TimeField()),
                ('period_seven_from', models.TimeField()),
                ('period_seven_to', models.TimeField()),
                ('period_eight_from', models.TimeField()),
                ('period_eight_to', models.TimeField()),
            ],
        ),
    ]
