# Generated by Django 5.0.2 on 2024-03-06 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_remove_classincharge_class_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAndTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grade')),
                ('period_five', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_five', to='school.timing')),
                ('period_five_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_five_subject', to='school.subject')),
                ('period_five_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_five_teacher', to='school.staff')),
                ('period_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_four', to='school.timing')),
                ('period_four_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_four_subject', to='school.subject')),
                ('period_four_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_four_teacher', to='school.staff')),
                ('period_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_one', to='school.timing')),
                ('period_one_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_one_subject', to='school.subject')),
                ('period_one_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_one_teacher', to='school.staff')),
                ('period_seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_seven', to='school.timing')),
                ('period_seven_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_seven_subject', to='school.subject')),
                ('period_seven_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_seven_teacher', to='school.staff')),
                ('period_six', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_six', to='school.timing')),
                ('period_six_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_six_subject', to='school.subject')),
                ('period_six_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_six_teacher', to='school.staff')),
                ('period_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_three', to='school.timing')),
                ('period_three_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_three_subject', to='school.subject')),
                ('period_three_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_three_teacher', to='school.staff')),
                ('period_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_two', to='school.timing')),
                ('period_two_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_two_subject', to='school.subject')),
                ('period_two_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_two_teacher', to='school.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ClassIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classandtiming')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staff')),
            ],
        ),
    ]
